server:
  port: 8501
spring:
  application:
    name: cloud-provider-payment-consul  # 微服务的服务名称

  # consul的配置
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
