server:
  port: 8503

spring:
  application:
    name: cloud-customer-payment-consul


  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}